use std::path::Path;
use std::{env, fs, io};

/// Every `.proto` in the fanout contract. All four are listed explicitly rather
/// than relying on `request`/`response` to pull `common`/`filters` in through
/// their imports: if an import is dropped, an explicit list keeps the types in
/// codegen instead of silently removing them.
const PROTOS: [&str; 4] = [
    "proto/v1/common.proto",
    "proto/v1/filters.proto",
    "proto/v1/request.proto",
    "proto/v1/response.proto",
];

/// prost names its output after the protobuf package, not after the directory
/// the sources live in.
const PROST_OUTPUT: &str = "valkey_timeseries.fanout.v1.rs";

/// The checked-in generated code, kept next to the schema it is derived from
/// rather than left in `OUT_DIR`, so that IDEs can index and navigate the wire
/// types and a schema change shows up as a reviewable diff. Wired into the crate
/// by a `#[path]` module in `src/commands/fanout_codec/mod.rs`.
const GENERATED: &str = concat!("proto/v1/generated/", "valkey_timeseries.fanout.v1.rs");

/// Set this to accept a schema change: it rewrites [`GENERATED`] in place.
const REGEN_ENV: &str = "VALKEY_TS_PROTO_REGEN";

const HEADER: &str = "\
// @generated by build.rs from proto/v1/*.proto
//
// Do not edit by hand. Change the .proto files, then run
// `VALKEY_TS_PROTO_REGEN=1 cargo build` and commit the result. A normal build
// compares this file against the schema and fails on a mismatch, so generated
// code cannot drift away from the contract unnoticed.

";

fn main() -> io::Result<()> {
    for proto in PROTOS {
        println!("cargo:rerun-if-changed={proto}");
    }
    println!("cargo:rerun-if-changed={GENERATED}");
    println!("cargo:rerun-if-env-changed={REGEN_ENV}");

    // Parse .proto sources into descriptors without requiring `protoc`.
    let file_descriptors = protox::compile(PROTOS, ["proto/"]).map_err(io::Error::other)?;

    let out_dir = env::var("OUT_DIR").map_err(|_| io::Error::other("OUT_DIR is not set"))?;

    let mut config = prost_build::Config::new();
    // prost-build defaults strip_enum_prefix=true, so the enum-name prefixes in
    // the .proto files (AGGREGATION_TYPE_ALL, etc.) produce zero Rust-side diff
    // — the generated variants stay `All`, `Min`, and so on.
    config
        .out_dir(&out_dir)
        .compile_fds(file_descriptors)
        .map_err(io::Error::other)?;

<<<<<<< HEAD
    let expected = format!(
        "{HEADER}{}",
        fs::read_to_string(Path::new(&out_dir).join(PROST_OUTPUT))?
    );
    let current = fs::read_to_string(GENERATED);

    if !current.as_deref().is_ok_and(|current| current == expected) {
        if env::var_os(REGEN_ENV).is_some() {
            if let Some(parent) = Path::new(GENERATED).parent() {
                fs::create_dir_all(parent)?;
            }
            fs::write(GENERATED, expected)?;
        } else {
            // Distinguish the two failures: a stale file means someone edited the
            // schema without regenerating, while a missing one usually means it
            // was never committed or got ignored — different mistakes with the
            // same remedy.
            let problem = if current.is_err() {
                "is missing"
            } else {
                "is out of date with the .proto sources"
            };
            return Err(io::Error::other(format!(
                "{GENERATED} {problem}.\n\
                 Regenerate and commit it:\n\n    {REGEN_ENV}=1 cargo build\n"
            )));
        }
    }

    // The promql surface has its own, unrelated proto contract; it is compiled
    // dynamically into OUT_DIR rather than checked in like the fanout wire types.
    println!("cargo:rerun-if-changed=src/promql/types.proto");
    prost_build::Config::new()
        .out_dir(&out_dir)
        .compile_protos(&["src/promql/types.proto"], &["src/"])
        .map_err(io::Error::other)?;

    // Generate one #[test] per `.test` file under the promqltest testdata
    // directory, included via
    // `include!(concat!(env!("OUT_DIR"), "/promql_tests_generated.rs"))`.
    println!("cargo:rerun-if-changed=src/promql/promqltest/testdata");
    let dest_path = Path::new(&out_dir).join("promql_tests_generated.rs");
    let testdata_dir = Path::new("src/promql/promqltest/testdata");
    let mut code = String::new();

    if testdata_dir.exists() {
        let mut entries: Vec<_> = fs::read_dir(testdata_dir)
            .expect("failed to read testdata directory")
            .filter_map(|e| e.ok())
            .filter(|e| {
                e.path()
                    .extension()
                    .and_then(|s| s.to_str())
                    .map(|s| s == "test")
                    .unwrap_or(false)
            })
            .collect();

        entries.sort_by_key(|e| e.file_name());

        code.push_str("use crate::promql::promqltest::runner::run_test;\n\n");
        for entry in entries {
            let path = entry.path();
            let stem = path
                .file_stem()
                .and_then(|s| s.to_str())
                .expect("invalid test filename");

            let fn_name = stem.replace('-', "_");

            code.push_str(&format!(
                r#"
#[test]
fn should_pass_{fn_name}() {{
    run_test("{stem}", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/promql/promqltest/testdata/{stem}.test")))
        .unwrap();
}}
"#,
            ));
        }
    }

    fs::write(&dest_path, code).map_err(io::Error::other)?;

    Ok(())
}
